const story = {
  1: { name: "Welcome to Vanguard Estates", children: [2, 3] },
  2: { name: "Stay at Vanguard", children: [6, 7] },
  3: { name: "Bring Him Home", children: [4, 5] },
  4: { name: "Buy A Home Robot", children: [8, 9] },
  5: { name: "Call Him More", children: [10, 11] },
  6: { name: "Use Drop-In", children: [12, 13] },
  7: { name: "Disable Drop-In", children: [14, 15] },
  8: { name: "Explain Missy", children: [16, 17] },
  9: { name: "Don't Explain Missy", children: [] },
  10: { name: "Install Cameras", children: [18, 19] },
  11: { name: "ove Him In", children: [20, 21] },
  12: { name: "Don't Tell Him", children: [22, 23] },
  13: { name: "Tell Him", children: [24, 25] },
  14: { name: "Robot Baths", children: [26, 27] },
  15: { name: "Human Baths", children: [] },
  16: { name: "Go To Manila", children: [] },
  17: { name: "Don't Go To Manila", children: [] },
  18: { name: "Handle it Yourself", children: [] },
  19: { name: "Pay for Help", children: [] },
  20: { name: "Drop Out of School", children: [] },
  21: { name: "Take Out a Loan", children: [] },
  22: { name: "Stop the Robot", children: [] },
  23: { name: "Trust the Robot", children: [] },
  24: { name: "Keep His Secret", children: [] },
  25: { name: "Report Him", children: [] },
  26: { name: "Break the News", children: [] },
  27: { name: "Keep Quiet", children: [] },
};

export default story;
